Generalized install info related to fwupd bug on Debian-based distros
GrapheneOS/grapheneos.org pull request #1091
Opened 2024-12-30 18:55 UTC by rslurry

Updated Web Install info related to issue #1088 about the fwupd bug in Debian and some Ubuntu versions.  This avoids unnecessarily stopping fwupd on releases that don't have the bug, and it keeps the guide generalized for applicability to other Debian- and Ubuntu-derived distros.  It won't need to be revisited until years from now when Debian and Ubuntu entirely drop support for the current releases that use the outdated fwupd version.

2024-12-30 18:57 UTC, thestinger requested changes
This needs to be kept in sync between the CLI and web install guides.

2024-12-30 18:58 UTC, thestinger requested changes

2024-12-30 18:58 UTC, thestinger commented on static/install/web.html
> +                    <li><a href="#working-around--bug-on-linux-distributions">Working around  bug on Linux distributions</a></li>
This looks accidental.

2024-12-30 19:01 UTC, rslurry commented on static/install/web.html
> +                    <li><a href="#working-around--bug-on-linux-distributions">Working around  bug on Linux distributions</a></li>
Huh, I didn't intentionally touch anything there - must have been an accident when Ctrl+F'ing for fwupd.  Thanks for catching that.

2024-12-30 19:05 UTC, rslurry commented
Alright, that accidental deletion was fixed, and the CLI guide was updated to match.

2025-01-25 17:20 UTC, rslurry commented
Hey there, just circling back now that the holidays have passed.  Are there any other changes you'd like to see before merging this PR?

2025-01-25 17:29 UTC, merged