Add Q&A about what 'not production-ready' means
GrapheneOS/grapheneos.org pull request #57
Opened 2020-02-20 10:58 UTC by Peter-Easton

2020-04-28 15:40 UTC, thestinger commented
It's no longer being described as not production ready. It's just not yet aimed at usage by most end users until the app repository need is addressed, among other things.

2020-04-28 15:41 UTC, thestinger requested changes
Can you reword this based on that?

2020-05-01 19:56 UTC, Peter-Easton commented
Sure. Will change it!

2020-05-01 20:16 UTC, Peter-Easton commented
There we go. I left most of it the same but I changed it to about being aimed at general end users.

2020-06-05 05:59 UTC, thestinger submitted a review, later dismissed

2020-06-05 06:00 UTC, thestinger requested changes
I think you need to make it much clearer that GrapheneOS is intended for this, but isn't ready yet. This makes it sound this it's not intended for this use case, rather than this being under development.

2020-06-05 06:50 UTC, Peter-Easton commented
I think I fixed it, how's it sound now?

2020-06-05 06:57 UTC, thestinger requested changes

2020-06-05 06:57 UTC, thestinger commented on static/faq.html
> +            security model. This choice to describe GrapheneOS as not being for most end users is
Can you say not yet here?

2020-06-05 21:36 UTC, Peter-Easton commented on static/faq.html
> +            security model. This choice to describe GrapheneOS as not being for most end users is
Okay, one moment...

2020-11-23 20:10 UTC, thestinger commented
I don't want to include this.

2020-11-23 20:10 UTC, closed without merging