Removed extra space in ` / ` string.
GrapheneOS/grapheneos.org pull request #592
Opened 2023-02-01 20:08 UTC by slashtab

Removed extra space in ` / ` string for uniformity across the site and better readability.

2023-02-02 01:28 UTC, thestinger commented
@slashtab A few of these should be undone because they're for multi-word alternatives such as AOSP / stock OS where there should be spaces around the slash. Can you go through them and remove those ones?

2023-02-02 04:07 UTC, r3g-5z requested changes
See the mentioned comments for dropping the changes to multi-word usages.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li>kernel (Pixel 4, Pixel 4 XL, Pixel 4a, Pixel 4a (5G), Pixel 5, Pixel 5a): use dynamic kernel modules matching AOSP/stock OS instead of using monolithic kernel builds to av
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li><a href="https://github.com/GrapheneOS/platform_manifest/releases/tag/SD2A.220601.004.B2.2022081800">SD2A.220601.004.B2.2022081800</a> (Pixel 6a) — early release for Pixel
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li><a href="https://github.com/GrapheneOS/platform_manifest/releases/tag/SD2A.220601.004.B2.2022081600">SD2A.220601.004.B2.2022081600</a> (Pixel 6a) — early release for Pixel
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li>Pixel 6a: switch to SD2A.220601.004.B2 (July 2022) device sources and vendor files (AOSP/stock OS patch level for Pixel 6a is still 2022-06-01 until Android 13)</li>
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li><a href="https://github.com/GrapheneOS/platform_manifest/releases/tag/SD2A.220601.004.2022080900">SD2A.220601.004.2022080900</a> (Pixel 6a) — early release for Pixel 6a wi
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li><a href="https://github.com/GrapheneOS/platform_manifest/releases/tag/SQ1D.211205.017.2022010500">SQ1D.211205.017.2022010500</a> (Pixel 6, Pixel 6 Pro) — early release wit
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li>kernel (Pixel 6, Pixel 6 Pro): update GKI base to android12-5.10-2021-12_r8 from the android12-5.10-2021-12_r6 version still used by the AOSP/stock Pixel OS March release
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li>Pixel 3, Pixel 3 XL, Pixel 3a, Pixel 3a XL, Pixel 4, Pixel 4 XL, Pixel 4a, Pixel 4a (5G), Pixel 5, Pixel 5a, Pixel 6, Pixel 6 Pro: remove AOSP/stock OS configuration pinni
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li><a href="https://github.com/GrapheneOS/platform_manifest/releases/tag/SD2A.220601.004.2022073000">SD2A.220601.004.2022073000</a> (Pixel 6a) — early release for Pixel 6a wi
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li><a href="https://github.com/GrapheneOS/platform_manifest/releases/tag/SD2A.220601.004.2022080300">SD2A.220601.004.2022080300</a> (Pixel 6a) — early release for Pixel 6a wi
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li><a href="https://github.com/GrapheneOS/platform_manifest/releases/tag/SD2A.220601.004.2022080500">SD2A.220601.004.2022080500</a> (Pixel 6a) — early release for Pixel 6a wi
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li>kernel (Pixel 6, Pixel 6 Pro, Pixel 6a): split raviole (Pixel 6, Pixel 6 Pro) and bluejay (Pixel 6a) kernels for now due to AOSP/stock OS differences</li>
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li>GmsCompatConfig: make sure Play Store PhenotypeFlags are overridable by Gservices flags (further deterring Play Store trying to update Play services/Play Store beyond supp
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/features.html
> +                        certificate/key expiry, etc.</li>
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/articles/server-traffic-shaping.html
> +                substantially reduce system calls/context switches by not triggering the
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/usage.html
> +                    capture images/record videos via the OS provided camera implementation.
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li>initial port to Android 11 with most GrapheneOS changes ported over (missing most SELinux policy hardening, some Pixel 4/4 XL kernel side channel mitigations, finer-graine
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, x86pup commented on static/releases.html
> +                        <li>use alternate grapheneos.online domain for connectivity check/captive portal fallback URLs to improve handling of future issues comparable to Quad9 temporarily blocking gr
This is a multi-word usage as mentioned, drop this change.

2023-02-02 04:07 UTC, r3g-5z commented on static/releases.html
> +                        <li>kernel (Pixel 4, Pixel 4 XL, Pixel 4a, Pixel 4a (5G), Pixel 5, Pixel 5a): enable forced kernel module signing with a per-build signing key (RSA 4096/sha256) as an addition
The space in this slash is intentional because these are RSA 4096 SHA 256 certificates (SHA256withRSA), this needs to be dropped too.

2023-02-02 04:07 UTC, r3g-5z commented on static/features.html
> +                                    <li>Forced kernel module signing with per-build RSA 4096/SHA256
The space in this slash is intentional because these are RSA 4096 SHA 256 certificates (SHA256withRSA), this needs to be dropped too.

2023-02-02 13:42 UTC, slashtab commented on static/usage.html
> +                    capture images/record videos via the OS provided camera implementation.
can I change it to `capture images or record videos`? or should drop to the original?

2023-02-02 14:04 UTC, slashtab commented
Thank you! @r3g-5z  and @thestinger . I have made all the suggested changes and waiting for review on one edit suggestion.

2023-02-02 16:13 UTC, x86pup commented on static/usage.html
> +                    capture images/record videos via the OS provided camera implementation.
Yes

2025-03-24 18:49 UTC, thestinger commented
https://github.com/GrapheneOS/grapheneos.org/pull/1140

2025-03-24 18:49 UTC, closed without merging